mileszs/wicked_pdf

lib/wicked_pdf/wicked_pdf_helper.rb, test/functional/wicked_pdf_helper_assets_test.rb
This one was a huge pain in the butt, and took a long time to find. But I found it!
=> Fixed check for HTTPS url instead of just HTTP url

README.md
Unless I'm missing something, this should be here.
Great lib, by the way. :)
=> Add missing `pdf =` assignment with example.

lib/wicked_pdf/wicked_pdf_helper.rb
Fix issue rendering stylesheets with embedded assets.  An example being custom fonts.
=> Fix issue rendering stylesheets with embedded assets

README.md
Adds information about the trailing nature of the binary wrapper.
=> About wrapped binary version

lib/wicked_pdf.rb
Source: http://www.dictionary.com/browse/retrieve
=> Fix spelling error: retreive -> retrieve

.travis.yml, Rakefile, lib/wicked_pdf/pdf_helper.rb, test/functional/pdf_helper_test.rb, test/functional/wicked_pdf_helper_assets_test.rb, test/unit/wicked_pdf_test.rb, wicked_pdf.gemspec
=> Ruby 2.3.0 to travis

README.md
Is this the current state of affairs? Ruby 2.2/Rails 4.2 is running in Travis.
=> Update version compatibility in README

README.md
=> [ci skip] Fix typo

test/fixtures/wicked.js, test/functional/wicked_pdf_helper_assets_test.rb, test/test_helper.rb
Add tests for these methods
* `wicked_pdf_stylesheet_link_tag`
* `wicked_pdf_image_tag`
* `wicked_pdf_javascript_include_tag`
=> Add test cases for `WickedPdfHelper::Assets`

lib/wicked_pdf/pdf_helper.rb, lib/wicked_pdf/railtie.rb
ref: #510 
I tried fix deprecation warning.
=> Fix Rails5 deprecation warning

README.md
This PR makes the badge icons render as SVG.
=> README: Use SVG badge icons

README.md
Looks like there's room for improvement ;) Let's remember about it.
=> Add CodeClimate badge to Readme

lib/wicked_pdf.rb, test/unit/wicked_pdf_test.rb
Following advice from issue #664, I added a unit test to verify it failed and added the recommended fix to make the test pass.
=> Added image and no_image parameters.

README.md
See https://github.com/mileszs/wicked_pdf/issues/714 and https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2184
=> Add caveat on different DPI scaling on Windows/Linux

README.md
https://www.codetriage.com/
This may help signal that this project is on CodeTriage, so potentially
issues and PRs might get emailed to people for visibility and help
fixing things or supporting others having trouble.
=> Add CodeTriage badge.

CHANGELOG.md, lib/wicked_pdf/version.rb, wicked_pdf.gemspec
And add CHANGELOG entries for significant changes since version 1.1.0.
Also add myself as an official author. I think I've been doing this long enough it's warranted.
=> Update VERSION to 1.2.0.

lib/wicked_pdf/progress.rb
=> Added check for Windows to prevent load of pty

README.md, lib/wicked_pdf/wicked_pdf_helper/assets.rb
This helper method supports stylesheets for Rails from webpacker gem.
=> Add support for webpacker stylesheets & Javascript

.travis.yml, Rakefile
=> Fix unit tests

CHANGELOG.md, README.md, lib/wicked_pdf/version.rb
Updated version to `2.0.0`, so we can have a release which plays nice with Rails 6 😄
=> Update to version 2.0.0

README.md, lib/wicked_pdf.rb, test/unit/wicked_pdf_test.rb
See https://github.com/wkhtmltopdf/wkhtmltopdf/pull/2341/commits/bac3fbf9eed3061399a4b528238c39535c2206c0
Thank you
=> Add support for --keep-relative-links flag

.rubocop_todo.yml, Rakefile, gemfiles/4.0.gemfile, gemfiles/4.1.gemfile, gemfiles/4.2.gemfile, gemfiles/5.0.gemfile, gemfiles/5.1.gemfile, gemfiles/5.2.gemfile, gemfiles/6.0.gemfile, gemfiles/rails_edge.gemfile, lib/wicked_pdf.rb, lib/wicked_pdf/option_parser.rb, lib/wicked_pdf/pdf_helper.rb, lib/wicked_pdf/railtie.rb, lib/wicked_pdf/wicked_pdf_helper/assets.rb, test/functional/pdf_helper_test.rb, test/unit/wicked_pdf_option_parser_test.rb, test/unit/wkhtmltopdf_location_test.rb, wicked_pdf.gemspec
Preventing CI builds from passing
=> Fix rubocop issues

README.md
info that I personally found really useful when learning how to use the gem + my experience
=> Readme - added more useful readings

CHANGELOG.md
There you go, I went through the whole history. And mark a few points that could have been releases.
I have tagged these that I noted locally. If you want, I can push and build .gem files if that is helpful.
Hopefully solves #1004
=> Update changelog with all versions

wicked_pdf.gemspec
I got an error with Rubocop when testing, so I updated the version.
=> Update Rubocop version

.github/workflows/ci.yml, gemfiles/5.2.gemfile, gemfiles/6.0.gemfile, gemfiles/6.1.gemfile, gemfiles/7.0.gemfile
You've added this commit in #998, but then deleted the changes in your 2nd commit
was that intentional ?
=> Test with Rails 7

README.md, lib/wicked_pdf/option_parser.rb, test/unit/wicked_pdf_option_parser_test.rb
adding support for _--allow_ option. to be used in conjunction with _--disable-local-file-access_
see: https://wkhtmltopdf.org/usage/wkhtmltopdf.txt
my first PR here, let me know if anything is needed to get this merged.
thanks!
=> add support for --allow option

lib/wicked_pdf.rb
=> Fix lint introduced with a recent PR

README.md, generators/wicked_pdf/templates/wicked_pdf.rb
Hello! Just some minor tweaks so the config example in the README is valid syntax and options in the template can be uncommented without modification. Cheers!
=> Update Config Example in README and template

README.md
https://github.com/mileszs/wicked_pdf/blob/master/.github/workflows/ci.yml
This CI matrix implies this gem works with newer Ruby/Rails versions.
=> Change "verified" versions in README
