mileszs/wicked_pdf

- README.md
- gemfiles/3.1.gemfile
- gemfiles/3.2.gemfile
- gemfiles/4.0.gemfile
- gemfiles/rails_edge.gemfile
- generators/wicked_pdf/templates/wicked_pdf.rb
I can change other files too if it's OK for you to use ruby > 1.9 hash styles. 
They are simplier and more beautiful :)
Also it's a little hard to use code from README because of list of old-styled hash in new Rails projects
> Changed old-style hashes to the new-style in readme and gemfiles

- lib/wicked_pdf.rb
`bundle exec which wkhtmltopdf` or `which wkhtmltopdf` should return empty
strings if nothing is found. Since an empty string is truthy, it'll prevent
`possible_locations` lookups from happening.
The fix is to make sure that a blank `which` will be converted to
something falsy.
> Fix bin path detection logic

- wicked_pdf.gemspec
This is a big speed bump for people who want to use wicked_pdf in a simple Ruby script.  For instance, now I need to install libxml2 because rails depends on nokogiri which depends on libxml2.
Since anyone who wants to use wicked_pdf in a Rails app will, by definition, already have rails loaded, it would seem there's no need to require it in the gemspec.  Confirm/deny?
> Remove rails dependency

- README.md
- lib/wicked_pdf.rb
Resolves issue #416 by adding `WickedPdf#pdf_from_url`. A fairly simple change. `pdf_from_html_file` is now just a special case of `pdf_from_url` with a URL scheme of `file://`.
> Add WickedPdf#pdf_from_url

- lib/wicked_pdf/wicked_pdf_helper.rb
Changed the add_extension method of WickedPdfHelper so it doesn't add the extension if the filename already has it.
> WickedPdfHelper.add_extension change

- lib/wicked_pdf.rb
- test/unit/wicked_pdf_test.rb
If options with a `--` prefix are given to `wkhtmltopdf` after an
object, they are swallowed. For instance, if a cover object and some
footer options are given, the footer will not be displayed.
This commits fixes this behavior by changing the order of the parsed
options.
> Fix parsed options order

- lib/wicked_pdf/wicked_pdf_helper.rb
Call to_s for people who might pass symbols/objects through as filenames.
The behavior got slightly changed in this merge:
https://github.com/mileszs/wicked_pdf/commit/656dd1591753d55db37bc446c8f231be9377b10a
> call to_s on file name for backwards compatibility

- lib/wicked_pdf/wicked_pdf_helper.rb
Fixes a bug where assets are sometimes parsed incorrectly from CSS files. Mentioned in #375.
> Fix bug parsing asset paths out of CSS

- lib/wicked_pdf.rb
This will resolve #441.
The issue was that that parts of the options hash in memory was being deleted which wicked_pdf parsed the options, specifically in my case, the [margins hash](https://github.com/mileszs/wicked_pdf/blob/be360d648388c48534263d7d3c7208ca43e58db8/lib/wicked_pdf.rb#L295). This resulted in those options going away for subsequent pdf generations after Rails initialization. This was specifically an issue when using the wicked_pdf middleware because the options are passed in once at initialization. Instead of deleting the in memory options, I'm making a duplicate of it and using that. I tested it on a local application and it resolved my issues.
> Uses a duplicate options hash when parsing options

- README.md
I updated the Page Numbering example to use decodeURIComponent() instead of the deprecated unescape().
> README Update: Replace the deprecated unescape() in the Page Numbering example.

- README.md
Minor adjustment and I'm not sure if you want this in there but I thought I would share it and give you the choice. It's what I'm using in my environment and it feels much nicer to just add `debug` onto the URL as opposed to `debug=1` to it.
Thanks so much, again, for creating this library. So money.
> Use `debug` instead of `debug=1`.

- lib/wicked_pdf/railtie.rb
- lib/wicked_pdf/wicked_pdf_helper.rb
- test/functional/wicked_pdf_helper_assets_test.rb
1. Fixed some handling for relative asset URLs getting protocols stuck onto them
2. Fixed detection of asset URLs that weren't surrounded by quotes
3. Expanded the AssetsTest and Railtie logic for more versions of Rails. If this is controversial I can split it into a new pull request.
> Asset URL fixes

- README.md
The no_background flag was documented, but no reference was made to the `background` flag.  To enable background-color in pdfs setting no_background to false does not work.  This seems a little illogical. So I hope this helps
> Adding missing background flag documentation

- .travis.yml
- lib/wicked_pdf.rb
- lib/wicked_pdf/middleware.rb
- lib/wicked_pdf/pdf_helper.rb
- lib/wicked_pdf/wicked_pdf_helper/assets.rb
- test/test_helper.rb
- test/unit/wicked_pdf_test.rb
* Update Travis file to test against ruby-head + use new Travis containers (roughly halves time test time)
* Some whitespace refactoring to reduce line length & improve readability 
* Fix some Rubocop complaints (mainly switching from `.gsub` to `.tr`)
> Changes for Rubocop + Travis

- CHANGLOG.md
- lib/wicked_pdf/pdf_helper.rb
The default dpi is now 72. Previously the default would be whatever your `wkhtmltopdf` version specified as the default.
> Default :dpi to '72'

- .travis.yml
- lib/wicked_pdf/wicked_pdf_helper/assets.rb
- test/functional/wicked_pdf_helper_assets_test.rb
- test/test_helper.rb
Compatibility with sprockets 3.0 was broken by that PR https://github.com/mileszs/wicked_pdf/pull/464. That PR also broke something else - CSS content like this "url(http://example.com/rails.png)" was removed.
This PR fixes compatibility with sprockets 3.0, reverts changes from #464 (but fixes its issues), and fixes some others issues. I added few new tests.
---
There is still one issue not fixed. When assets digest is enabled and assets compilation is enabled (default rails development configuration) and we have css(scss) like this:
img { image-url("rails.png"); }
this css is read as
img { url("/assets/rails-6fba03f13d6ff1553477dba03475c4b9b02542e9fb8913bd63c258f4de5b48d9.png"); }
and later it is changed to
img { url("file:////home/user/project/public/assets/rails-6fba03f13d6ff1553477dba0 …
> Fix #476 issue - problem with sprockets 3.0

- lib/wicked_pdf/pdf_helper.rb
In Ruby 2.3.0:
```
lib/wicked_pdf/pdf_helper.rb:2: warning: loading in progress, circular require considered harmful
<spew>
```
> Removes circular require from lib/wicked_pdf/pdf_helper.rb

- lib/wicked_pdf/pdf_helper.rb
- wicked_pdf.gemspec
On 2.3.0 (fairly stock):
```
wicked_pdf/wicked_pdf.gemspec:16: warning: global variable `$INPUT_RECORD_SEPARATOR' not initialize
```
> Input record separator

- lib/wicked_pdf/pdf_helper.rb
- test/functional/pdf_helper_test.rb
- test/functional/wicked_pdf_helper_assets_test.rb
- test/unit/wicked_pdf_test.rb
- wicked_pdf.gemspec
On 2.3.0 (fairly stock):
```
warning: ambiguous first argument; put parentheses or a space even after `/' operator
```
Switched to `%r` for the offending regular expressions.
> Regex ambiquity

- Rakefile
- lib/wicked_pdf/pdf_helper.rb
- test/functional/pdf_helper_test.rb
- test/functional/wicked_pdf_helper_assets_test.rb
- test/unit/wicked_pdf_test.rb
- wicked_pdf.gemspec
```
test/dummy/db/schema.rb doesn't exist yet. Run `rake db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter test/dummy/config/application.rb to limit the frameworks that will be loaded.
```
Using touch in `setup_and_run_tests` to create a blank schema file in the dummy Rails application for tests.
> Test schema warning

- test/unit/wicked_pdf_test.rb
We had a new WickedPdf instance being created in `test/unit/wicked_pdf_test.rb`.
Figured we should use it throughout rather than instantiating a fresh one in many of the tests.
> Test refactor

- README.md
- lib/wicked_pdf.rb
`--window-status="ready"` is an alternative to `--javascript-delay=5000` useful when the delay might be highly variable. wkhtmltopdf waits until some JS sets `window.status === "ready"` before rendering the HTML. A very useful option for this gem to allow.
> Add window_status flag

- .travis.yml
- Rakefile
- lib/wicked_pdf.rb
- test/functional/pdf_helper_test.rb
- test/functional/wicked_pdf_helper_assets_test.rb
- test/unit/wicked_pdf_test.rb
- wicked_pdf.gemspec
Fixes the existing Rubocop errors and runs Rubucop in CI.
This should prevent future PRs like this. 😉 
Also, the `rubocop` `rake` task had a guard clause that was `return`ing, which is not allowed. This caused it to bomb on Ruby 1.9.2 in CI. I changed it to `next` which seems to be the proper way to do it.
If you want any of the Rubocop rules disabled instead, let me know.
> Fix Rubocop errors and enforce in CI

- README.md
This adds reference about how `wkhtmltopdf` binary options can be set from the gem usage.
> Additional documentation about wkhtmltopdf binary options

- README.md
Adds the very helpful alternative to `wicked_pdf_helpers` from https://github.com/mileszs/wicked_pdf/issues/257#issuecomment-25708179 to the README.
> Add doc about alternative to wicked_pdf_helpers

- .travis.yml
Only Ruby 2.2.2 or newer can run Rails 5.0.
ref: https://github.com/rails/rails/blob/v5.0.0.rc1/guides/source/getting_started.md#guide-assumptions
> Remove not runnable Rails versions from CI

- lib/wicked_pdf/pdf_helper.rb
`PdfHelper` module does not directly depend on 'tempfile'.
In this gem `WickedPdfTempfile` depends on 'tempfile'
and `PdfHelper` depends on `WickedPdfTempfile`.
So we need not to require 'tempfile' in `PdfHelper`.
> Remove unnecessary require.

- .travis.yml
Only Ruby 2.2.2 or newer can run Rails 5.0.
ref: https://github.com/rails/rails/blob/v5.0.0.rc1/guides/source/getting_started.md#guide-assumptions
> Make test to be runnable on Ruby 2.2 x Rails Edge

- Rakefile
`$ rake dummy_generate` executes `touch new test/dummy/db/schema.rb`,
this generates unnecessary "new" file.
This commit prevent to create "new" file.
> Do not touch `new` file

- test/functional/pdf_helper_test.rb
- test/functional/wicked_pdf_helper_test.rb
Many test cases in `pdf_helper_test.rb` and
`wicked_pdf_helper_test.rb` are asserted only
Rails 2. But we can run some of them.
To increase test coverage, assert these test cases
in all Rails versions.
> To test as far as possible

- lib/wicked_pdf/pdf_helper.rb
- lib/wicked_pdf/railtie.rb
- lib/wicked_pdf/tempfile.rb
- lib/wicked_pdf/wicked_pdf_helper.rb
- lib/wicked_pdf/wicked_pdf_helper/assets.rb
- test/functional/wicked_pdf_helper_assets_test.rb
- test/functional/wicked_pdf_helper_test.rb
It is not good to expose modules and classes except the root
namespace (`WickedPdf`), because someone define same name
modules or classes.
In this case, `PdfHelper` is a very common name for someone
to define a same name module.
> Move all modules and classes into `WickedPdf` namespace

- lib/wicked_pdf.rb
Set `no_stop_slow_scripts` as `:boolean` for prevent its value passing (--no-stop-slow-scripts argument has no value)
If any `:boolean` option has `false` value, option not passes as command line argument (`make_option` method)
> No values arguments processing

- test/unit/wicked_pdf_test.rb
Rubocop currently provides two error messages on the master branch.  This fixes them.
```
....................C
Offenses:
test/unit/wicked_pdf_test.rb:64:18: C: Use 0o for octal literals.
File.chmod 0000, fp
^^^^
test/unit/wicked_pdf_test.rb:77:18: C: Use 0o for octal literals.
File.chmod 0777, fp
^^^^
```
> Fix rubocop compliants on octal literals.

- lib/wicked_pdf/wicked_pdf_helper/assets.rb
With `config.assets.compile` set to `false` (which it is by default in production in Rails 5), `Rails.application.assets` returns nil. In that case, we can call `Sprockets::Railtie.build_environment(Rails.application).find_asset` in place of `Rails.application.assets.find_asset`.
> Find assets via build_environment in Sprockets 3.

- README.md
`default_protocol` is an available config option that is not documented anywhere. Add it to the list of available options so that others can configure WickedPdf fully.
> default_protocol in list of available config

- README.md
Hello,
It might be obvious how to use 
```
render_to_string('templates/pdf', layout: 'pdfs/layout_pdf.html')
```
method, but I faced the same issue several times: if footer / header is used with **content** option, PDF is generated with multiple footers for every string of a general template, if there is no **layout** option. No errors, no warnings 🤔 And templates look fine and everything is fine ("I just fix some css" 😄) but PDF contains 64 pages with footers. A couple of hours later I got it: the document was an incorrect HTML document.
I've added examples and a note, I think it can be helpful
> Update README.md with examples for Super Advanced Usage

- CHANGELOG.md
Looks like there was a typo in the release date for v1.1.0 on the CHANGELOG in 6392bea1fe3a41682dfd7c20fd9c179b5a758f59, since Rubygems (and the date that commit was created) shows it was released on August 30th, not Sept 30th.
Also, there should be a `tag` pushed to the repository for that release, which is currently missing.
> Fix typo for release date of v1.1.0 in CHANGELOG.md

- lib/wicked_pdf.rb
- lib/wicked_pdf/railtie.rb
Gems like rails-html-sanitizer open `Rails` module without
actually requiring Rails. Instead check if Rails.env is defined.
Similar to: https://github.com/rails/activeresource/pull/216
> Handle Rails module defined without Rails env

- lib/wicked_pdf/wicked_pdf_helper.rb
Thank you for your nice gem.
I found Travis CI tests with Rails edge(5.1.0 beta) gemfile are failed by `NameError: uninitialized constant Mime::JS`.
In Rails 5.1.0 beta, `::Mime::JS` and other constants are removed by this [PR](https://github.com/rails/rails/pull/26746/files#diff-c5146df11f35304765e9ceebed108f57).
I fixed this problem using `::Mime[:js]`.
But in Rails 2.3, `::Mime[:js]` cannot be used because `::Mime.[]` is not defined.
So I checked `::Mime.[]` is defined or not using `respond_to?`, and if `::Mime.[]` is not defined, then I use `::Mime::JS`.
Please check my PR.
Thank you.
> Fix NameError: uninitialized constant Mime::JS in Rails 5.1.0 beta

- lib/wicked_pdf/wicked_pdf_helper/assets.rb
Pathname attr reader was removed/deprecated. Only filename is available in Sprockets 4.x.
> Assets helper Sprockets 4 compatibility fix.

- .travis.yml
- lib/wicked_pdf.rb
- lib/wicked_pdf/pdf_helper.rb
The `****************WICKED****************` log is unnecessary, as are the extra `*`'s around the command.
Instead of using `*`, prefix the actual command with `[wicked_pdf]:` to make it easier to identify the source of the command.
> Remove extraneous logging.

- lib/wicked_pdf/pdf_helper.rb
- test/functional/pdf_helper_test.rb
After upgrading to rails 5 we found that the way wicked_pdf prepends `ActionController::Base#render` causes an infinite loop when combined with another gem prepending render.
I believe our issue is generally related to https://github.com/mileszs/wicked_pdf/issues/111, though this PR focuses on prepend behavior.
The loop happens because wicked_pdf is not using the traditional prepend inheritance pattern, which looks like this
``` ruby
class Base
def render
end
end
class Patch
def render
patched_behavior
super
end
end
Base.prepend(Patch)
```
Instead, PdfHelper aliases the current render method away, then defines its own render method _on the base class_, which then calls the new render_with_wicked_pdf method.
If any other gem prepends its own render method using the inheritance pattern, …
> Use inheritance when prepending - Fixes conflict with other render gems

- test/functional/pdf_helper_test.rb
The last Travis CI build is failed due to rubocop errors.
```
Offenses:
test/functional/pdf_helper_test.rb:17:5: C: Put empty method definitions on a single line.
def render_to_string ...
^^^^^^^^^^^^^^^^^^^^
test/functional/pdf_helper_test.rb:20:5: C: Put empty method definitions on a single line.
def self.after_action(_) ...
^^^^^^^^^^^^^^^^^^^^^^^^
```
By default rubocop configuration, empty method definitions must be written in one line like `def empty_method; end`.
http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/EmptyMethod
So I fixed those errors to modify empty method definitions written in one line.
If you don't like one line method definition, it can be resolved by adding following configuration to [rubocop.yml](https://github.com/mileszs/wicked_pdf/blob/master/.rubocop.yml …
> Fix rubocop error

- lib/wicked_pdf.rb
If running in an environment where the HOME environment variable is not set, then the File.expand_path possibly called later on would throw a `couldn't find HOME environment -- expanding ~` error. This fixes it by only appending `~/bin` to the search path if the HOME environment variable is actually set.
> Fix wkhtmltopdf path detection when HOME environment variable is unset

- lib/wicked_pdf/pdf_helper.rb
New pull request without failing code for Rails versions > 3 (didn't test for earlier). As suggested, the correct hook is being called if defined, otherwise failing gracefully.
Thanks for the tips!
> Fix Rails 5 deprecation notice with conditional calling of appropriate hook

- wicked_pdf.gemspec
This information will appear on the gem's page on rubygems.org.
http://guides.rubygems.org/specification-reference/#requirements
> Add gemspec requirements attribute

- lib/wicked_pdf/pdf_helper.rb
- test/functional/pdf_helper_test.rb
https://github.com/mileszs/wicked_pdf/pull/630 used `after_action` in place of `after_filter` when it's available, since `after_filter` is deprecated in Rails 5.0. However, it was checking if the base class responded to `after_action?` (with a question mark appended) by accident.
> Fix method name when checking if controllers respond to `after_action`

- lib/wicked_pdf/wicked_pdf_helper/assets.rb
First, thanks for wicked_pdf! :green_heart: 
Ran into this problem while upgrading sprockets on our application
a rather lengthy debugging session through sprockets and friends
ended up here showing that the asset could be found if the
base_path was supplied. Iirc it's optional and should only
help - tbh it's a bit ago so don't have all the code in my
head anymore :)
edit: also we are running this in production so at least for us it works (tm) with the newest sprockets
> Provide the base_path for asset lookup

- wicked_pdf.gemspec
Tests are currently failing, and emitting this message:
```
Mocha::NotInitializedError: Mocha methods cannot be used outside the context of a test
```
This PR attempts to fix the tests so that other contributions can be evaluatated.
Ideally, we can also fix whatever is causing this in newer versions.
> Pin to older mocha version

- README.md
It took me a while to figure this out and the article in the wiki is outdated. I think this is a use case people will find useful to read about on the readme.
> Add help documentation for adding to email

- lib/wicked_pdf.rb
- test/unit/wkhtmltopdf_location_test.rb
Currently, `wicked_pdf` suffers from the same issue the `pdfkit` does (according to pdfkit/pdfkit#388) where it picks up warning information introduced in `bundle 1.4.x` when the `HOME` environment variable points to a non-writable directory. When the information is not specified by configuration and the `wicked_pdf` is being used in a `bundler` environment, `wicked_pdf` attempts to use `bundle exec which wkhtmltopdf` which will output something like:
```
`/not/a/writable/directory` is not a directory.
Bundler will use `/tmp/bundler/home/travis' as your home directory temporarily.
/usr/bin/wkhtmltopdf
```
Which will then trigger a failure in [`WickedPdf#initialize`] caused by getting the full text above from the call to the shell in …
> Avoid using the shell to locate wkhtmltopdf in a Bundler environment

- README.md
- lib/wicked_pdf.rb
Issue: When image assets fail to download from the web (return non 200 statuses).  We want to throw an exception.
Passing `extra: '--load-media-error-handling abort'` to WickedPdf should fail the pdf generation.  But it doesnt.  This seems to be because the underlying library `wkhtmltopdf` doesnt return the correct exit code it only returns error output.
Solution: enable a flag in wicked_pdf that will raise an exception if there is any output to stderr.
```
raise_on_all_errors: true
```
> Raise exception on all pdf generation errors

- README.md
I noticed the word "background" had been misspelt in the README, here is a PR fixing that. Also included are two other changes I noticed while reading through the file :)
> Updated spelling in the README

- .travis.yml
- Rakefile
- gemfiles/3.1.gemfile
- gemfiles/5.1.gemfile
- gemfiles/5.2.gemfile
- test/fixtures/database.yml
- wicked_pdf.gemspec
Fix CI test suite
- Force bundler 1.x for most versions
- Add workaround for Ruby 2.3 bundler
- Fix sqlite3 issues
- Add new versions of Ruby and Rails
> Fix CI test suite

- lib/wicked_pdf/pdf_helper.rb
Rails 5 supports an `assigns` option to `render`/`render_to_string` that allows setting instance variables available to the template. This is particularly handy for rendering outside of controllers where these instance variables wouldn't otherwise be available.
It's a pass-through so I didn't add any new tests (but could.)
> respect rails 5 `assigns` render option

- README.md
- lib/wicked_pdf/pdf_helper.rb
It was discovered that we don't pass the `inline` option through to `render` in #797.
This PR adds support for this option when used with `render pdf: 'mypdf'`.
> Support render inline option.

- .travis.yml
- wicked_pdf.gemspec
5.2 started failing due to Bundler 1 and 2 differences.
This uses a variable dependency for the gem, and some overrides in the `.travis.yml` file.
> Fix CI build

- lib/wicked_pdf/railtie.rb
In #810 It was discovered that version `1.2.0` was released with an issue that would result in a `SystemStackError (stack level too deep)`.
I believe this has to do with the usage of `alias_method_chain` applied to `ActionController::Base#render`, which may also be tampered with by something else in the `Gemfile`.
> Use module#prepend when available.

- lib/wicked_pdf/railtie.rb
If remotipart is loaded after wicked_pdf, it's aliasing of `render`
causes it to call render in an endless loop causing a SystemStackError.
This forces the WickedPdf railtie to initialize only after remotipart
has already aliased `render`, so that when we call render, it's the
remotipart alias.
> Avoid conflict with remotipart.

- README.md
I would much prefer to label each option with the version of wkhtmltopdf that is required to use it, and possibly commands for older or newer versions, but I don't have to time to verify that and will be more difficult to maintain. Ultimately, the source of truth should be the wkhtmltopdf docs of your specific version. But this note at least warns the user about this requirement.
Fixes #478.
> Add note about options based on wkhtmltopdf version.

- README.md
- lib/wicked_pdf.rb
Without the ability to override it, `--log-level info` is implied when `wkhtmltopdf` executes. This - for some unholy reason - sends progress messages to stderr, which has the unfortunate side-effect of making WickedPdf panic dramatically over successfully completed tasks when run with `raise_on_all_errors: true`.
The intent of the changes herein is to ensure sensible behavior when running with `log_level: 'error', raise_on_all_errors: true`.
> Add support for --log-level option

- lib/wicked_pdf/wicked_pdf_helper/assets.rb
`Rails.configuration.assets` will be undefined if asset pipeline is not being used, which leads to an error why trying to check the value of `assets.compile`.
This is primarily a problem when using the webpacker helpers (b/c no sprockets) and only in non-dev environments (b/c this logic gets short-circuited if there's a webpack dev server running.)
`Rails.configuration.assets` is referred to in one other place but it's a block that's only run in Rails 3 so presumably doesn't need to be updated.
> Fix Webpacker helpers in production env

- wicked_pdf.gemspec
Hi guys
This PR is linked to the issue [#855](https://github.com/mileszs/wicked_pdf/issues/855)
The idea is to add the metadata hash into the gemspec file so the changelog_uri is listed as a changelog link in the side panel on RubyGems.org website.
I hope it's all good.
Tks
Leandro.
> Add rubygems metadata hash into the gemspec file

- .rubocop.yml
- .rubocop_todo.yml
- .travis.yml
- Rakefile
- gemfiles/4.0.gemfile
- gemfiles/4.1.gemfile
- gemfiles/4.2.gemfile
- gemfiles/5.0.gemfile
- gemfiles/5.1.gemfile
- gemfiles/5.2.gemfile
- gemfiles/6.0.gemfile
- lib/wicked_pdf/railtie.rb
- test/fixtures/manifest.js
- test/test_helper.rb
- wicked_pdf.gemspec
In rails 6 wicked_pdf initializer causes 
> DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper.
>
> Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.
> ...
because of early access to `ActionController::Base` and can be fixed by lazy loading.
This PR fixes it by using `ActiveSupport.on_load` (supported since rails 3) 
Also made tests pass on ruby 2.6 and fresh gem versions (had to lock sprockets to 3 because of changed newline handling)
> Support for rails 6

- lib/wicked_pdf/wicked_pdf_helper/assets.rb
open-uri is a security vulnerability https://sakurity.com/blog/2015/02/28/openuri.html
Net::HTTP.get is available on all supported rubies >= 2.2
Fixes #863
> Replace open-uri with net/http

- CHANGELOG.md
- lib/wicked_pdf/wicked_pdf_helper/assets.rb
Added force encoding to UTF-8 to fix rendering of PDFs with UTF characters.
Fixes #893
> Force UTF-8 encoding

- .rubocop.yml
- README.md
- lib/wicked_pdf/wicked_pdf_helper/assets.rb
Introduces a helper method to access webpacked assets directly.
e.g:
`image_tag wicked_pdf_asset_pack_path("media/images/foobar.png")`
> Support webpacker assets

- README.md
I was looking for this options, I find it strange to have it for the `header` and `footer` options, but not the main one... Digging into the code reveals that it actually exists.
So I suggest adding it in the README.
Thanks for this nice gem!
> [DOC] add 'locals' option to the README advanced section

- README.md
- lib/wicked_pdf.rb
- test/unit/wicked_pdf_test.rb
@unixmonkey  @mileszs  👍 
The 0.12.6 version of wkhtmltopdf  has a breaking change option, that is true by default, related to local file access. 
Link for breaking change in WkHtmlToPDF 0.12.6:
https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.6
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4536
https://github.com/wkhtmltopdf/wkhtmltopdf/blob/0.12.6/src/shared/commonarguments.cc#L227-L228
The local file access, that was enabled by default in <= 0.12.5, now is false by default in 0.12.6+
> Add a option to disable/enable local file access, that is enabled by default in 0.12.5 and false by default in 0.12.6 version of wkhtmltopdf

- generators/wicked_pdf/templates/wicked_pdf.rb
- lib/wicked_pdf.rb
Hi,
so I really struggled to get `wkhtmltopdf` (which is obviously used by `wicked_pdf`) working without having an X server running on my virtual server. Unfortunately, the best solution I found, was to wrap all `wkhtmltopdf` around the `xvfb-run` command which is - from my understanding - emulating an X server for systems where a real X server is not available. Doing so, made my PDF's generating normally again.
I'm not really sure whether there's any better solution. I didn't find anything working so far besides the approach I'm following.
As there are many topics/issues about generating PDF's without an X server being available, I decided to propose my code changes to `wicked_pdf`. Let's discuss whether this is a good approach or if you see anything else, which seems to be more …
> Add option `use_xvfb` to emulate an X server

- .rubocop_todo.yml
- lib/wicked_pdf.rb
This PR fixes issues raised by rubocop.
> Make the CI green again

- lib/wicked_pdf.rb
- lib/wicked_pdf/binary.rb
- test/unit/wicked_pdf_binary_test.rb
- test/unit/wicked_pdf_test.rb
Cleans up main class and allows refactoring of path handling.
Binary path discovery can be complex it seems and this offers a path to improved handling or overriding if necessary. 
Long term goal of combining extracted option parsing and this to allow a command class to combine and execute and return result.
I think these combined PRs provide a path to a well factored and a cleaner handling gem's functions.
> Encapsulate binary path and version handling

- wicked_pdf.gemspec
When running the tests for local dev for the first time I ran into a few issues. 
Firstly the bundler version in Ruby >= 2.5 was pegged to bundler >= 2. I don't think this necessary as I am happily continuing to use bundler v1.17.x for the moment and didn't want to be forced to upgrade. So I have relaxed the bundler version to use what is currently installed since there is no dependency on v2 in the core code.
Also added bootsnap since the dummy app requires it when booting.
> Adjust gemspec development dependencies

- lib/wicked_pdf.rb
- lib/wicked_pdf/pdf_helper.rb
The reason for not wanting to unlink them is primariily for debugging. If an error occurs, the `wkhtmltopdf` command that had problems is shown as part of the error message. Something like this: 
```
Failed to execute:
["/Users/me/.rbenv/versions/2.6.5/bin/wkhtmltopdf", "--enable-local-file-access", "--disable-smart-shrinking", "--orientation", "Portrait", "--page-size", "Letter", "--margin-top", "27", "--margin-bottom", "19", "--header-html", "file:////var/folders/9n/vjrv4bzs7fxf6crkdc84tf740000gn/T/wicked_header_pdf20201023-55115-le3quo.html", "--footer-html", "file:////var/folders/9n/vjrv4bzs7fxf6crkdc84tf740000gn/T/wicked_footer_pdf20201023-55115-1o98lhe.html", "file:////var/folders/9n/vjrv4bzs7fxf6crkdc84tf740000gn/T/wicked_pdf20201023-55115-1am8ara.html", …
```
> Do not unlink HTML temp files immediately.

- lib/wicked_pdf/wicked_pdf_helper/assets.rb
_We're using this in production to solve our problem. Looking to get some feedback from @mileszs before finalizing this properly and, hopefully, getting it merged to help others in similar situations._
Using URLs to reference images can cause a lot of problems with wkhtmltopdf, particularly when used in the header and footer. It produces errors such as "Too many open files" as well as buffer/stack overflows. These issues can be seen here, among other places: 
- https://github.com/mileszs/wicked_pdf/issues/288
- https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1819
- https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3019
- https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2093
- https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4762
- https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3081 …
> Add `wicked_pdf_url_base64`.

- lib/wicked_pdf.rb
When the HTML content and generated PDF files get too large (how large is "too large" depends on your system, OS, config and available resources), trying to read all of the content into memory can lead to `Errno::EINVAL` errors like `Invalid argument @ io_fread` and `Invalid argument @ io_write`.
Initially, I thought this was a `wkhtmltopdf` issue so I posted [an Issue there](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4859) instead and quickly discovered the error was happening in `wicked_pdf` prior to running the `wkhtmltopdf` command.
Instead of reading this content entirely into memory, this content should be read in chunks to save memory usage.
After some benchmarking, a chunk size of 1MB was picked (`1024 * 1024`). Here are the benchmarks comparing different methods and chunk …
> Read HTML string and generated PDF file in chunks.

- lib/wicked_pdf.rb
- lib/wicked_pdf/option_parser.rb
- lib/wicked_pdf/pdf_helper.rb
- lib/wicked_pdf/tempfile.rb
In https://github.com/mileszs/wicked_pdf/pull/949 we made it so that files are written to and read from in chunks, which improves outcomes when creating large PDFs on memory-constrained system. This PR extracts this work into the `WickedPdf::Tempfile` class to clean up the main `pdf_from_string` and `pdf_from_url` methods.
> Extract reading and writing files in chunks

- lib/wicked_pdf/pdf_helper.rb
- lib/wicked_pdf/railtie.rb
Since rails < 4 and ruby < 2.2 are unsupported, we can assume that `ActionController::Base.after_action` and `Module.prepend` exist.
This fixes https://github.com/github/view_component/issues/288 , and should fix #111 (but didn't test)
> Remove code for unsupported rails and ruby versions

- README.md
I wanted to also add driftingruby (their wicked_pdf video is under a paywall) & gorails (they don't have)
> readme - add links to couple of screencasts

- lib/wicked_pdf/wicked_pdf_helper/assets.rb
Since the change in #973, I've experienced an issue where images are not
being embedding in the pdf generated (in non development environments)
when using the following:
```
image_tag wicked_pdf_asset_pack_path("static/example.png")
```
For context: The pdfs are being generated via a background job on a
separate sever to the webapp, so using the `asset_host` option is not
ideal, as the pdf would then need to fetch the assets from another server
when they're already available locally. Although not ideal, I have tried setting
`Rails.application.config.asset_host` via `production.rb` to no avail.
This commit reinstates the original functionality prior to #973, whist
still retaining the new functionality add via #973.
> fix: `webpacker_source_url`

- lib/wicked_pdf/wicked_pdf_helper/assets.rb
Webpacker's version check is failed if webpacker follows for wicked_pdf in Gemfile. 
Webpacker is not defined at the gem initialization in the case. 
```ruby
require 'net/http'
require 'webpacker/version' if defined?(Webpacker)
```
`Webpacker::VERSION` constant not defined unless 'webpacker/version' required. And `webpacker_source_url(source)` returns `nil`
```ruby
def webpacker_source_url(source)
return unless defined?(Webpacker) && defined?(Webpacker::VERSION)
...
end
```
> Fix check webpacker version

- lib/wicked_pdf/railtie.rb
We ran into some problems using this gem with our Rails 6 app that adds a lot of custom paths to Zeitwerk's autoloaders. Narrowed it down to the view helper being included in `ActionView::Base` during the action_controller load hook rather than in the action_view load hook.
This change fixed the issue for us, and it feels better than accessing a private method.
> Include view helper on view load.

- lib/wicked_pdf/wicked_pdf_helper/assets.rb
This adds support to [rails/propshaft](https://github.com/rails/propshaft) asset pipeline introduced recently.
Basically it wraps `Propshaft::Assets` class and adds some methods to be compatible with existing `Sprockets::Asset` api
> Add support for Propshaft asset pipeline

- lib/wicked_pdf/wicked_pdf_helper/assets.rb
When running wicked_pdf with ruby 2.7 in a non-rails environment the following error is encountered:
`uninitialized constant WickedPdf::WickedPdfHelper::Assets::SimpleDelegator`
The delegate library was loaded by default in older versions of ruby, but in 2.7 this is not the case. Explicitly requiring delegate in assets.rb resolves the issue.
> "require 'delegate'" for compatibility with ruby 2.7

- lib/wicked_pdf/binary.rb
This PR follows up on #816 - I _think_ it's a simple typo.
Fixes #1022
> Fix a typo of #possible_binary_locations

- wicked_pdf.gemspec
This gem exposes no executables.
> Drop unused executables gemspec directive

- wicked_pdf.gemspec
Hi!
Bumping rubocop to the most recent version as we are using wicked_pdf in production but it's preventing us from running a more recent version of rubocop that supports Ruby 3.2
> Bump rubocop to 1.46

- lib/wicked_pdf.rb
- lib/wicked_pdf/option_parser.rb
Fix issue #1031. 
Header/footer generated by `WickedPdf::Tempfile` is deleted before wkhtmltopdf called. 
This PR try to use normal `File` then delete it when the pdf file generated. 
Temporary fix in your Gemfile.
`gem 'wicked_pdf', git: 'https://github.com/thanhcuong1990/wicked_pdf.git', branch: 'master'`
> Fix header/footer temp file is removed before wkhtmltopdf called

- lib/wicked_pdf/tempfile.rb
- lib/wicked_pdf/wicked_pdf_helper/assets.rb
Hello! 
I upgraded to Ruby 3.1, and when I did i started receiving errors that uninitialized constant StringIO (NameError).  I feel this is similar to the PR for require delegate that had been addressed earlier.  
https://github.com/mileszs/wicked_pdf/pull/1019/files
When running WickedPDF via the ruby command using ruby 3.1, I received
```
/usr/local/rvm/rubies/ruby-3.1.3/lib/ruby/3.1.0/delegate.rb:61:in `const_get': uninitialized constant StringIO (NameError)
```
when running the following command
```
"bundle exec ruby -e 'require \"wicked_pdf\"; WickedPdf.new.pdf_from_string(\"<p>Ya did it</p>\"); puts \"great!"'"
```
In all examples I've seen this used, we should first require this. 
https://ruby-doc.org/stdlib-2.5.1/libdoc/stringio/rdoc/StringIO.html
Thank you
> require stringio before use

- lib/wicked_pdf/wicked_pdf_helper/assets.rb
Hi!
I'm using `wicked_pdf` in a project where assets are being delivered with `shakapacker` version `7` .
I ran into an issue where the following error message was raised when I tried to use pack asset helpers:
```
cannot load such file -- webpacker/version (LoadError)
```
I've seen that this issue has already been reported here: https://github.com/mileszs/wicked_pdf/issues/1066
I've found out that this line was raising the error:
`lib/wicked_pdf/wicked_pdf_helper/assets.rb :237`
```ruby
require 'webpacker/version'
```
Shakapacker started renaming their entire project from `webpacker` to `shakapacker` .
See the changelog for details: https://github.com/shakacode/shakapacker/blob/master/CHANGELOG.md#changed
> _Rename Webpacker to Shakapacker in the entire project including config files, …
> Shakapacker 7 compatibility (#1066)

- lib/wicked_pdf/progress.rb
Add support for truffleruby (22.1.0). 
Cause this feature is not supported by truffleruby (22.1.0) yet: https://github.com/oracle/truffleruby/blob/master/doc/user/compatibility.md#standard-libraries
Without commit PR got error:
```
<internal:core> core/kernel.rb:236:in `gem_original_require': cannot load such file -- pty (LoadError)
from /root/.rbenv/versions/truffleruby+graalvm-22.1.0/graalvm/languages/ruby/lib/gems/gems/wicked_pdf-2.6.3/lib/wicked_pdf/progress.rb:3:in `<module:Progress>'
from /root/.rbenv/versions/truffleruby+graalvm-22.1.0/graalvm/languages/ruby/lib/gems/gems/wicked_pdf-2.6.3/lib/wicked_pdf/progress.rb:2:in `<class:WickedPdf>'
from /root/.rbenv/versions/truffleruby+graalvm-22.1.0/graalvm/languages/ruby/lib/gems/gems/wicked_pdf-2.6.3/lib/wicked_pdf/progress.rb:1:in …
```
> Add support for truffleruby (22.1.0) on Linux

- CHANGELOG.md
- lib/wicked_pdf/wicked_pdf_helper/assets.rb
We get the following error after replacing Sprockets with Propshaft:
`ActionView::Template::Error (incompatible character encodings: ASCII-8BIT and UTF-8)`
This fix resolves the issue.
Propshaft::Asset#content returns an ASCII-8BIT encoded string because it's using File::binread under the hood so the encoding needs to be set to UTF-8 if it's a JS or CSS file.
> Fix Propshaft encoding issue

- lib/wicked_pdf/wicked_pdf_helper/assets.rb
As explain in #1098 this PR https://github.com/mileszs/wicked_pdf/pull/1067 broke compatibility with `Webpacker`
The following line has been removed, resulting in an error when trying to access `Webpacker::VERSION`
```ruby
require 'webpacker/version'
```
Re add the `require 'webpacker/version'` and for consistency also add `require 'shakapacker/version'` when using `Shakapacker`
I tested it on our code base and our test suite is green. 
Ideally someone using `Shakapacker` would give this ago as well
> Fix webpacker compatibility

- README.md
- generators/wicked_pdf/templates/wicked_pdf.rb
- lib/wicked_pdf.rb
- test/test_helper.rb
- test/unit/wicked_pdf_test.rb
Adds the `WickedPdf.configure` method described in #1089. Also adds a deprecation warning for `WickedPdf.config=` which can be silenced.
> Add WickedPdf.configure method

- lib/wicked_pdf.rb
resolved #1109
Loading of "ostruct" depends on Rake, so we need to explicitly load it and resolve the dependency.
Because Rake does not load "ostruct" since version 13.2.0.
https://github.com/ruby/rake/pull/545
> fix: OpenStruct causes NameError in Rake13.2.0

- lib/wicked_pdf/wicked_pdf_helper/assets.rb
- test/fixtures/subdirectory/nested.js
- test/functional/wicked_pdf_helper_assets_test.rb
- test/test_helper.rb
This PR fixes the issues reported after #1094 and related to the asset manifest implementation not looking for the assets properly.
---
As a side note, this will most likely be my last contribution to this project. The fix itself took me 5 minutes to implement but adding those four simple test cases took... 1.5h. I wish I was joking 🥲
If anyone still has energy it would be great to at least figure out how to upgrade Mocha to the newer version as this one has a bug that prevents stubs from clearing properly (though it would be amazing to get rid of it completely and switch to rspec)
> Fix: Ensure assets without extensions are handled correctly

- lib/wicked_pdf/tempfile.rb
Cf. https://gist.github.com/fxn/bf4eed2505c76f4fca03ab48c43adc72
Hi, 
This is a simple fix for a case of a string being mutated while frozen ( with `frozen_string_literal` true)
I believe to enable this gem to be compliant with the future in ruby, and following the recommandations of the aforementionned gist, It would be good to enable the frozen string literal RUBYOPTion in CI
> Fix for frozen string literal to prepare for ruby 3.4

- wicked_pdf.gemspec
Starting from Ruby 3.5.0, `ostruct` will no longer be included as a default gem. This means that it must be added to the gemspec.
Here is the deprecation message:
```
/Users/garyhtou/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75: warning: /Users/garyhtou/.rbenv/versions/3.3.5/lib/ruby/3.3.0/ostruct.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
Also please contact the author of wicked_pdf-2.8.1 to request adding ostruct into its gemspec.
```
Closes https://github.com/mileszs/wicked_pdf/issues/1129
> Add `ostruct` as dependency for Ruby 3.5.0

- lib/wicked_pdf.rb
- lib/wicked_pdf/binary.rb
- lib/wicked_pdf/middleware.rb
- lib/wicked_pdf/option_parser.rb
- lib/wicked_pdf/pdf_helper.rb
- lib/wicked_pdf/progress.rb
- lib/wicked_pdf/railtie.rb
- lib/wicked_pdf/tempfile.rb
- lib/wicked_pdf/version.rb
- lib/wicked_pdf/wicked_pdf_helper.rb
- lib/wicked_pdf/wicked_pdf_helper/assets.rb
> Add frozen_string_literal magic header

- lib/wicked_pdf/binary.rb
Close unneeded pipes when wkhtmltopdf checking version.
Unless we close the stdin and stderr pipes in Open3, this command will hang when running under Ruby 3.1 (and possibly ruby 3.0 too).
According to [the documentation](https://docs.ruby-lang.org/en/2.0.0/Open3.html#method-i-popen3) these pipes should be closed explicitly when in block form (like we are using).
Note: This only happens for me when I'm also using a bunch of older/outdated gems (specifically, `eye`, which uses `celluloid`, `celluloid-io`, `kostya-sigar` and `state_machines` gems). If I'm not including these gems (via `ey`) in my project, this problem doesn't occur
> Version check hangs on ruby 3 with certain gem combination

- lib/wicked_pdf/wicked_pdf_helper/assets.rb
[rails/propshaft](https://github.com/rails/propshaft) support was added with #1010
However it appears to only work with dynamic assets and fails with precompiled ones:
```
#<UncaughtThrowError: uncaught throw #<ActionView::Template::Error: undefined local variable or method `content' for an instance of WickedPdf::WickedPdfHelper::Assets::PropshaftAsset>>
```
Improve the original solution and use Propshaft's built-in [resolver](https://github.com/rails/propshaft/blob/main/lib/propshaft/assembly.rb#L21) to handle gracefully both asset types
> Allow/Fix precompiled assets with Propshaft pipeline
